version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: '.env'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    image: spanish_bot:latest
    env_file: '.env'
    command: ["python", "-m", "src.main"]
    depends_on:
      db:
        condition: service_healthy
  
networks:
  default:
    name: service_netwok